export const footerLinks = [
  {
    title: "Droom for Individuals",
    links: [
      { name: "Buy", src: "/buy" },
      { name: "Get Loan", src: "/get-loan" },
      { name: "Buy Inspection Services", src: "/inspection-services" },
      { name: "How Droom Works", src: "/how-droom-works" },
      { name: "How Droom Builds Trust", src: "/builds-trust" },
      { name: "FAQs", src: "/faqs" },
      { name: "Buyer's Guide", src: "/buyers-guide" },
      { name: "Make Most of Droom", src: "/make-most-of-droom" },
      { name: "Tips", src: "/tips" },
      { name: "Buyer Surety", src: "/buyer-surety" },
      { name: "Individual Fee And Charges", src: "/fees-and-charges" },
      {
        name: "Return, Refund And Cancellation Policy",
        src: "/return-refund-policy",
      },
      { name: "Testimonials", src: "/testimonials" },
      { name: "Concierge", src: "/concierge" },
    ],
  },
  {
    title: "Droom Marketplace for ProSellers",
    links: [
      { name: "Sign-Up As Dealer And Seller", src: "/dealer-signup" },
      { name: "ProSeller Services: Dealer | OEM", src: "/proseller-services" },
      { name: "Plans & Pricing", src: "/pricing" },
      { name: "How Droom Works For Dealers", src: "/how-it-works-dealers" },
      { name: "Why Droom", src: "/why-droom" },
      { name: "Why E-Commerce", src: "/why-ecommerce" },
      { name: "FAQ's", src: "/dealer-faqs" },
      { name: "Seller Policies & Rules", src: "/seller-policies" },
      { name: "Dealer Fee & Charges", src: "/dealer-fees" },
      { name: "Dealer Tips & Advice", src: "/dealer-tips" },
      { name: "Payment Policies", src: "/payment-policies" },
      { name: "Seller Screening System", src: "/seller-screening" },
      { name: "StoreManager Highlights", src: "/store-manager" },
      { name: "Droom University", src: "/droom-university" },
      { name: "Testimonials", src: "/dealer-testimonials" },
    ],
  },
  {
    title: "Droom Discovery",
    links: [
      { name: "Vehicle Research", src: "/vehicle-research" },
      { name: "Vehicle Finder", src: "/vehicle-finder" },
      { name: "Check Price", src: "/check-price" },
      { name: "Repair Estimates", src: "/repair-estimates" },
      { name: "TCO", src: "/tco" },
      { name: "Compare Vehicle", src: "/compare-vehicle" },
      { name: "EMI Calculator", src: "/emi-calculator" },
      { name: "Dashboard", src: "/dashboard" },
      { name: "Droom Suggests", src: "/droom-suggests" },
      { name: "Top 10", src: "/top-10" },
      { name: "Affordability Calculator", src: "/affordability-calculator" },
      { name: "By The Budget", src: "/by-budget" },
      { name: "Fuel Efficiency", src: "/fuel-efficiency" },
      { name: "Driving School", src: "/driving-school" },
      { name: "Expert Reviews", src: "/expert-reviews" },
      { name: "Droom Rating", src: "/droom-rating" },
      { name: "Brochures", src: "/brochures" },
    ],
  },
  {
    title: "Droom for Business",
    links: [
      {
        name: "Automobile Certification Services",
        src: "/certification-services",
      },
      { name: "E-Commerce Solutions", src: "/ecommerce-solutions" },
      { name: "Advertise With Droom", src: "/advertise" },
      { name: "Marketing Services", src: "/marketing-services" },
      { name: "Financial Services", src: "/financial-services" },
      { name: "Industry Research", src: "/industry-research" },
    ],
  },
  {
    title: "About Us",
    links: [
      { name: "About Droom", src: "/about" },
      { name: "Career", src: "/careers" },
      { name: "Press Kit", src: "/press-kit" },
      { name: "Blogs", src: "/blogs" },
      { name: "News", src: "/news" },
      { name: "Videos", src: "/videos" },
      { name: "Investor Relations", src: "/investor-relations" },
      { name: "Impact", src: "/impact" },
      { name: "Droom Labs", src: "/droom-labs" },
      { name: "Droom: Celebrating 10 Years", src: "/10-years" },
      { name: "Contact Us", src: "/contact" },
    ],
  },
];
