export type VehicleCard = {
  id: string;
  imageUrl: string;
  price: number;
  year: number;
  make: string;
  model: string;
  variant: string;
  type: "car" | "bike";
};

export const carCards: VehicleCard[] = [
  {
    id: "car-1",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Swift",
    price: 764112,
    year: 2020,
    make: "Maruti Suzuki",
    model: "Swift",
    variant: "ALPHA 1.2",
  },
  {
    id: "car-2",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Baleno",
    price: 689000,
    year: 2019,
    make: "Maruti Suzuki",
    model: "Baleno",
    variant: "ZETA 1.2",
  },
  {
    id: "car-3",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Creta",
    price: 1287000,
    year: 2021,
    make: "Hyundai",
    model: "Creta",
    variant: "1.5 SX CVT",
  },
  {
    id: "car-4",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Venue",
    price: 699000,
    year: 2019,
    make: "Hyundai",
    model: "Venue",
    variant: "S Turbo",
  },
  {
    id: "car-5",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Grand+i10",
    price: 869900,
    year: 2020,
    make: "Hyundai",
    model: "Grand i10 Nios",
    variant: "ASTA 1.2 MT",
  },
  {
    id: "car-6",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=City",
    price: 1099000,
    year: 2021,
    make: "Honda",
    model: "City",
    variant: "VX CVT",
  },
  {
    id: "car-7",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Amaze",
    price: 649000,
    year: 2018,
    make: "Honda",
    model: "Amaze",
    variant: "1.2 S MT",
  },
  {
    id: "car-8",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Verna",
    price: 945000,
    year: 2020,
    make: "Hyundai",
    model: "Verna",
    variant: "SX 1.5",
  },
  {
    id: "car-9",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Slavia",
    price: 1349000,
    year: 2022,
    make: "Skoda",
    model: "Slavia",
    variant: "1.5 Style",
  },
  {
    id: "car-10",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Kushaq",
    price: 1199000,
    year: 2021,
    make: "Skoda",
    model: "Kushaq",
    variant: "Ambition 1.0",
  },
  {
    id: "car-11",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Nexon",
    price: 879000,
    year: 2020,
    make: "Tata",
    model: "Nexon",
    variant: "XZ Plus",
  },
  {
    id: "car-12",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Altroz",
    price: 649000,
    year: 2021,
    make: "Tata",
    model: "Altroz",
    variant: "XZ Petrol",
  },
  {
    id: "car-13",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Harrier",
    price: 1549000,
    year: 2022,
    make: "Tata",
    model: "Harrier",
    variant: "XZA Plus",
  },
  {
    id: "car-14",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Seltos",
    price: 1249000,
    year: 2021,
    make: "Kia",
    model: "Seltos",
    variant: "GT Line",
  },
  {
    id: "car-15",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Sonet",
    price: 899000,
    year: 2020,
    make: "Kia",
    model: "Sonet",
    variant: "HTX Turbo",
  },
  {
    id: "car-16",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Innova",
    price: 1899000,
    year: 2021,
    make: "Toyota",
    model: "Innova Crysta",
    variant: "2.4 ZX",
  },
  {
    id: "car-17",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Fortuner",
    price: 3299000,
    year: 2022,
    make: "Toyota",
    model: "Fortuner",
    variant: "4x2 AT",
  },
  {
    id: "car-18",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Ecosport",
    price: 849000,
    year: 2019,
    make: "Ford",
    model: "EcoSport",
    variant: "Titanium",
  },
  {
    id: "car-19",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Compass",
    price: 1749000,
    year: 2021,
    make: "Jeep",
    model: "Compass",
    variant: "Limited Plus",
  },
  {
    id: "car-20",
    type: "car",
    imageUrl: "https://via.placeholder.com/120x80?text=Polo",
    price: 799000,
    year: 2018,
    make: "Volkswagen",
    model: "Polo",
    variant: "GT TSI",
  },
];

export const bikeCards: VehicleCard[] = [
  {
    id: "bike-1",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Classic+350",
    price: 189000,
    year: 2021,
    make: "Royal Enfield",
    model: "Classic 350",
    variant: "Signals",
  },
  {
    id: "bike-2",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Bullet",
    price: 159000,
    year: 2020,
    make: "Royal Enfield",
    model: "Bullet 350",
    variant: "ES",
  },
  {
    id: "bike-3",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Hunter+350",
    price: 149900,
    year: 2022,
    make: "Royal Enfield",
    model: "Hunter 350",
    variant: "Metro",
  },
  {
    id: "bike-4",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=R15",
    price: 182000,
    year: 2021,
    make: "Yamaha",
    model: "R15 V4",
    variant: "M",
  },
  {
    id: "bike-5",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=MT+15",
    price: 168000,
    year: 2021,
    make: "Yamaha",
    model: "MT 15",
    variant: "V2",
  },
  {
    id: "bike-6",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=FZ",
    price: 129000,
    year: 2019,
    make: "Yamaha",
    model: "FZ S",
    variant: "V3",
  },
  {
    id: "bike-7",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Apache+160",
    price: 119000,
    year: 2020,
    make: "TVS",
    model: "Apache RTR 160",
    variant: "4V",
  },
  {
    id: "bike-8",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Apache+200",
    price: 139000,
    year: 2021,
    make: "TVS",
    model: "Apache RTR 200",
    variant: "Race Edition",
  },
  {
    id: "bike-9",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Jupiter",
    price: 72000,
    year: 2020,
    make: "TVS",
    model: "Jupiter",
    variant: "ZX",
  },
  {
    id: "bike-10",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Activa",
    price: 76000,
    year: 2021,
    make: "Honda",
    model: "Activa 6G",
    variant: "Standard",
  },
  {
    id: "bike-11",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Shine",
    price: 72000,
    year: 2019,
    make: "Honda",
    model: "Shine",
    variant: "Drum",
  },
  {
    id: "bike-12",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Hornet",
    price: 129000,
    year: 2020,
    make: "Honda",
    model: "Hornet 2.0",
    variant: "ABS",
  },
  {
    id: "bike-13",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Dominar",
    price: 219000,
    year: 2021,
    make: "Bajaj",
    model: "Dominar 400",
    variant: "Touring",
  },
  {
    id: "bike-14",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Pulsar+NS200",
    price: 139000,
    year: 2020,
    make: "Bajaj",
    model: "Pulsar NS200",
    variant: "ABS",
  },
  {
    id: "bike-15",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Pulsar+150",
    price: 109000,
    year: 2019,
    make: "Bajaj",
    model: "Pulsar 150",
    variant: "Twin Disc",
  },
  {
    id: "bike-16",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=RC+390",
    price: 299000,
    year: 2022,
    make: "KTM",
    model: "RC 390",
    variant: "BS6",
  },
  {
    id: "bike-17",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Duke+250",
    price: 239000,
    year: 2021,
    make: "KTM",
    model: "Duke 250",
    variant: "Standard",
  },
  {
    id: "bike-18",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Gixxer",
    price: 124000,
    year: 2020,
    make: "Suzuki",
    model: "Gixxer",
    variant: "SF",
  },
  {
    id: "bike-19",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=Access+125",
    price: 78000,
    year: 2021,
    make: "Suzuki",
    model: "Access 125",
    variant: "Disc",
  },
  {
    id: "bike-20",
    type: "bike",
    imageUrl: "https://via.placeholder.com/120x80?text=CB350",
    price: 199000,
    year: 2022,
    make: "Honda",
    model: "CB350",
    variant: "DLX Pro",
  },
];